In [3]:
import pandas as pd 
from matplotlib import pyplot as plt

In [5]:
LNPost = pd.read_csv("postings.csv")
LNPost.head(10)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
5,91700727,Downtown Raleigh Alliance,Economic Development and Planning Intern,Job summary:The Economic Development & Plannin...,20.0,HOURLY,"Raleigh, NC",1481176.0,9.0,NaN,...,NaN,1.713456e+12,NaN,0,INTERNSHIP,USD,BASE_SALARY,35360.0,27601.0,37183.0
6,103254301,Raw Cereal,Producer,Company DescriptionRaw Cereal is a creative de...,300000.0,YEARLY,United States,81942316.0,7.0,NaN,...,NaN,1.712861e+12,NaN,0,CONTRACT,USD,BASE_SALARY,180000.0,NaN,NaN
7,112576855,NaN,Building Engineer,Summary: Due to the pending retirement of our ...,120000.0,YEARLY,"San Francisco, CA",NaN,2.0,NaN,...,NaN,1.712443e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,105000.0,94101.0,6075.0
8,1218575,Children's Nebraska,Respiratory Therapist,"At Children’s, the region’s only full-service ...",NaN,NaN,"Omaha, NE",721189.0,3.0,NaN,...,• Requires the ability to communicate effectiv...,1.712348e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,68102.0,31055.0
9,2264355,Bay West Church,Worship Leader,It is an exciting time to be a part of our chu...,NaN,MONTHLY,"Palm Bay, FL",28631247.0,5.0,350.0,...,"Knowledge, Skills and Abilities: 1. Proficient...",1.712456e+12,NaN,0,PART_TIME,USD,BASE_SALARY,4200.0,32905.0,12009.0

In [6]:
num_rows = len(LNPost)
print("Number of rows:", num_rows)

Number of rows: 123849

In [9]:
LNPost.keys

<bound method NDFrame.keys of             job_id                     company_name  \
0           921716            Corcoran Sawyer Smith
1          1829192                              NaN
2         10998357           The National Exemplar
3         23221523           Abrams Fensterman, LLP
4         35982263                              NaN
...            ...                              ...
123844  3906267117                     Lozano Smith
123845  3906267126                        Pinterest
123846  3906267131                     EPS Learning
123847  3906267195  Trelleborg Applied Technologies
123848  3906267224                        Solugenix

                                                    title  \
0                                   Marketing Coordinator
1                       Mental Health Therapist/Counselor
2                             Assitant Restaurant Manager
3       Senior Elder Law / Trusts and Estates Associat...
4                                      Service Technician
...                                                   ...
123844                   Title IX/Investigations Attorney
123845       Staff Software Engineer, ML Serving Platform
123846               Account Executive, Oregon/Washington
123847                       Business Development Manager
123848                  Marketing Social Media Specialist

                                              description  max_salary  \
0       Job descriptionA leading real estate firm in N...        20.0
1       At Aspen Therapy and Wellness , we are committ...        50.0
2       The National Exemplar is accepting application...     65000.0
3       Senior Associate Attorney - Elder Law / Trusts...    175000.0
4       Looking for HVAC service tech with experience ...     80000.0
...                                                   ...         ...
123844  Our Walnut Creek office is currently seeking a...    195000.0
123845  About Pinterest:\n\nMillions of people across ...         NaN
123846  Company Overview\n\nEPS Learning is a leading ...         NaN
123847  The Business Development Manager is a 'hunter'...         NaN
123848  Marketing Social Media Specialist - $70k – $75...     75000.0

       pay_period                 location  company_id  views  med_salary  \
0          HOURLY            Princeton, NJ   2774458.0   20.0         NaN
1          HOURLY         Fort Collins, CO         NaN    1.0         NaN
2          YEARLY           Cincinnati, OH  64896719.0    8.0         NaN
3          YEARLY        New Hyde Park, NY    766262.0   16.0         NaN
4          YEARLY           Burlington, IA         NaN    3.0         NaN
...           ...                      ...         ...    ...         ...
123844     YEARLY         Walnut Creek, CA     56120.0    1.0         NaN
123845        NaN            United States   1124131.0    3.0         NaN
123846        NaN              Spokane, WA  90552133.0    3.0         NaN
123847        NaN     Texas, United States   2793699.0    4.0         NaN
123848     YEARLY  San Juan Capistrano, CA     43325.0    2.0         NaN

        ...                                        skills_desc   listed_time  \
0       ...  Requirements: \n\nWe are seeking a College or ...  1.713398e+12
1       ...                                                NaN  1.712858e+12
2       ...  We are currently accepting resumes for FOH - A...  1.713278e+12
3       ...  This position requires a baseline understandin...  1.712896e+12
4       ...                                                NaN  1.713452e+12
...     ...                                                ...           ...
123844  ...                                                NaN  1.713571e+12
123845  ...                                                NaN  1.713572e+12
123846  ...                                                NaN  1.713572e+12
123847  ...                                                NaN  1.713573e+12
123848  ...                                                NaN  1.713573e+12

                    posting_domain  sponsored  work_type currency  \
0                              NaN          0  FULL_TIME      USD
1                              NaN          0  FULL_TIME      USD
2                              NaN          0  FULL_TIME      USD
3                              NaN          0  FULL_TIME      USD
4                              NaN          0  FULL_TIME      USD
...                            ...        ...        ...      ...
123844                         NaN          0  FULL_TIME      USD
123845    www.pinterestcareers.com          0  FULL_TIME      NaN
123846  epsoperations.bamboohr.com          0  FULL_TIME      NaN
123847                         NaN          0  FULL_TIME      NaN
123848                         NaN          0  FULL_TIME      USD

       compensation_type normalized_salary  zip_code     fips
0            BASE_SALARY           38480.0    8540.0  34021.0
1            BASE_SALARY           83200.0   80521.0   8069.0
2            BASE_SALARY           55000.0   45202.0  39061.0
3            BASE_SALARY          157500.0   11040.0  36059.0
4            BASE_SALARY           70000.0   52601.0  19057.0
...                  ...               ...       ...      ...
123844       BASE_SALARY          157500.0   94595.0   6013.0
123845               NaN               NaN       NaN      NaN
123846               NaN               NaN   99201.0  53063.0
123847               NaN               NaN       NaN      NaN
123848       BASE_SALARY           72500.0   92675.0   6059.0

[123849 rows x 31 columns]>

In [8]:
LNPost.columns

Index(['job_id', 'company_name', 'title', 'description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'med_salary',
       'min_salary', 'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'skills_desc', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

## Colummns that would be benficial to my project: 
job id
company name 
job title 
skills_desc

In [10]:
LNPost = LNPost.drop(['description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'med_salary',
       'min_salary', 'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'], 
        axis = 1) 
print (LNPost.head())

     job_id            company_name  \
0    921716   Corcoran Sawyer Smith
1   1829192                     NaN
2  10998357  The National Exemplar
3  23221523  Abrams Fensterman, LLP
4  35982263                     NaN

                                               title  \
0                              Marketing Coordinator
1                  Mental Health Therapist/Counselor
2                        Assitant Restaurant Manager
3  Senior Elder Law / Trusts and Estates Associat...
4                                 Service Technician

                                         skills_desc
0  Requirements: \n\nWe are seeking a College or ...
1                                                NaN
2  We are currently accepting resumes for FOH - A...
3  This position requires a baseline understandin...
4                                                NaN

I asked chatgpt how to select out the columns of the data set but I feel like I'm mising steps before this ⏬️

In [12]:
selected_columns = LNPost['job_id','company_id', 'title', 'skills_desc']

print(selected_columns)

KeyError: ('job_id', 'company_id', 'title', 'skills_desc')

In [13]:
selected_columns = LNPost.loc[:,['job_id','company_id', 'title', 'skills_desc']]

print(selected_columns)

KeyError: "['company_id'] not in index"

## I'm a bit frustrated by these errors simply because I'm realizing I may have to get very creative with all the data I may find. Also tracking the background of where data comes from and how accurate it is will also prove to be a challenge. I'm really focusing on collecting as much data as possible in this milstone and narrowing down how it can be used and what factors I want to consider.Tthen the process of cleaning, analyzing and creating graphics that can be apart of my final presentation will be the focus of milstone two.